// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package data

import (
	"context"
)

type Querier interface {
	Delete(ctx context.Context, id int32) error
	DeleteByID(ctx context.Context, id int32) error
	GetAll(ctx context.Context, arg GetAllParams) ([]User, error)
	GetByEmail(ctx context.Context, email string) (User, error)
	GetOne(ctx context.Context, id int32) (User, error)
	Insert(ctx context.Context, arg InsertParams) (User, error)
	Update(ctx context.Context, arg UpdateParams) (User, error)
}

var _ Querier = (*Queries)(nil)
